
###### USER ###### 
USER_NAME_MIN = 2
USER_NAME_MAX = 20
USER_EMAIL_MAX = 50
USER_PASSWORD_MIN = 8
USER_PASSWORD_MAX = 20
USER_PHONE_MIN = 8
USER_PHONE_MAX = 20

###### RECIPE ###### 
RECIPE_TITLE_MIN = 2
RECIPE_TITLE_MAX = 50
RECIPE_DESCRIPTION_MIN = 50
RECIPE_DESCRIPTION_MAX = 255   
RECIPE_SERVINGS_MIN = 1
RECIPE_SERVINGS_MAX = 10
RECIPE_MINUTES_MIN = 0
RECIPE_MINUTES_MAX = 1440

INGRIDIENT_NAME_MAX = 50       
INGRIDIENT_AMOUNT_MAX = 10
INGRIDIENT_UNITS = ["", "g", "kg", "ml", "L", "tsp", "tbsp", "pinch", "pcs"]
RECIPE_INGRIDIENTS_MAX = 30

INSTRUCTION_MIN = 5
INSTRUCTION_MAX = 500
RECIPE_STEPS_MAX = 30

###### IMAGE UPLOAD ###### 
IMAGE_EXTENSIONS = {"png", "jpg", "jpeg", "webp"}
IMAGE_MAX_MB = 2


###### REGEX ###### 
REGEX_ID = "^[0-9a-f]{32}$"
REGEX_USER_EMAIL = r"^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$"
REGEX_USER_NAME = f"^.{{{USER_NAME_MIN},{USER_NAME_MAX}}}$"
REGEX_USER_PASSWORD = f"^.{{{USER_PASSWORD_MIN},{USER_PASSWORD_MAX}}}$"
REGEX_USER_PHONE = f"^\\+?[0-9 ]{{{USER_PHONE_MIN},{USER_PHONE_MAX}}}$"
REGEX_RECIPE_TITLE = f"^.{{{RECIPE_TITLE_MIN},{RECIPE_TITLE_MAX}}}$"
REGEX_WHOLE_NUMBER = "^[0-9]{1,4}$"
REGEX_INGRIDIENT_AMOUNT = "^[0-9]+(\\.[0-9]+)?$"